// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// A fixed UUID used as the dummy user when auth is bypassed.
const DUMMY_USER_ID = "00000000-0000-0000-0000-000000000000";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.warn("[auth-middleware] Missing Supabase env vars — proceeding with bypassed auth.");
    }

    // Use the service_role key if available so we can bypass RLS for the dummy user.
    // Otherwise fall back to the publishable (anon) key.
    const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

    const supabase = createClient<Database>(
      SUPABASE_URL || "https://dummy.supabase.co",
      SUPABASE_SERVICE_ROLE_KEY || SUPABASE_PUBLISHABLE_KEY || "dummy-key",
      {
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      },
    );

    return next({
      context: {
        supabase,
        userId: DUMMY_USER_ID,
        claims: { sub: DUMMY_USER_ID },
      },
    });
  },
);
